name: SAM Deploy

on:
  push:
    branches:
      - main  # ou a branch que deseja monitorar

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # substitua pela região correta

    - name: Install AWS SAM CLI
      run: |
        sudo apt update
        sudo apt install -y awscli
        sudo apt install -y python3-pip
        sudo pip3 install aws-sam-cli

    - name: Build SAM application
      run: sam build

    - name: Deploy SAM application
      run: sam deploy --stack-name lambda-authorizer-client-stack --no-confirm-changeset --no-fail-on-empty-changeset
